[package]
name = "doodle"
version = "0.1.0"
authors = ["imhenoch <isidro.henoch@gmail.com>"]

[dependencies]
glib = "^0"
gio = "^0"
gdk = "^0"
gdk-pixbuf = "^0"
gtk = "^0"
random-access-disk = "0.4.0"
